version: '3.8'

services:

  postgres:
    image: postgres:13
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRESDB}
      POSTGRES_USER: ${POSTGRESUSER}
      POSTGRES_PASSWORD: ${POSTGRESPASSWORD}
      POSTGRES_HOST: ${POSTGRESHOST}
    ports:
      - "5432:5432"
  
  django:
    build: .
    command: >
      sh -c "python3 manage.py makemigrations &&
            python3 manage.py migrate &&
            python3 manage.py runserver 0.0.0.0:8080"
    ports:
      - 8080:8080
    environment:
      - POSTGRESDB=${POSTGRESDB}
      - POSTGRESUSER=${POSTGRESUSER}
      - POSTGRESPASSWORD=${POSTGRESPASSWORD}
      - POSTGRESCONTAINER=${POSTGRESCONTAINER}
      - POSTGRESPORT=${POSTGRESPORT}
    depends_on:
      - postgres
    volumes:
      - .:/app


volumes:
  postgres_data: