version: '3.8'

services:

  postgres:
    image: postgres:13
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRESDB}
      POSTGRES_USER: ${POSTGRESUSER}
      POSTGRES_PASSWORD: ${POSTGRESPASSWORD}
      POSTGRES_HOST: ${POSTGRESHOST}
    ports:
      - "5432:5432"
  
  django:
    build: .
    command: >
      sh -c "python3 manage.py makemigrations &&
            python3 manage.py migrate &&
            uvicorn notification_service.asgi:application --host 0.0.0.0 --port 8080"
    ports:
      - 8080:8080
    environment:
      - POSTGRESDB=${POSTGRESDB}
      - POSTGRESUSER=${POSTGRESUSER}
      - POSTGRESPASSWORD=${POSTGRESPASSWORD}
      - POSTGRESCONTAINER=${POSTGRESCONTAINER}
      - POSTGRESPORT=${POSTGRESPORT}
    depends_on:
      - postgres
    volumes:
      - .:/app
    
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  
  email_service:
    build:
      context: .
      dockerfile: workers/email/Dockerfile
    container_name: email_container
    ports:
      - "465:465"
    depends_on:
      - rabbitmq
      - redis
  
  sms_service:
    build:
      context: .
      dockerfile: workers/sms/Dockerfile
    container_name: sms_container
    depends_on:
      - rabbitmq
      - redis

    



volumes:
  postgres_data: