version: '3.8'

services:

  postgres:
    image: postgres:13
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRESDB}
      POSTGRES_USER: ${POSTGRESUSER}
      POSTGRES_PASSWORD: ${POSTGRESPASSWORD}
      POSTGRES_HOST: ${POSTGRESHOST}
    ports:
      - "${POSTGRESPORT}:${POSTGRESPORT}"
  
  django:
    build: .
    command: "python3 manage.py runserver 0.0.0.0:8080"
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - .:/app





volumes:
  postgres_data: